import { Talent, Brand, BrandSku, BookingCampaign, BookingShift, UserAccount, ChatConversation, ChatMessage, TaskItem } from "@/types";

export const MOCK_USERS: UserAccount[] = [
  {
    id: "usr-admin",
    fullName: "Phạm Quốc Hùng",
    email: "admin@liveagency.vn",
    phone: "0987654321",
    password: "123456",
    avatarUrl: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
    role: "ADMIN",
    department: "Ban Giám Đốc",
    status: "ACTIVE",
    createdAt: "2026-01-01",
    permissions: {
      manageTalents: true,
      manageCampaigns: true,
      manageSchedule: true,
      viewReports: true,
      manageSettings: true,
      manageUsers: true,
      contactTalent: true,
    },
  },
  {
    id: "usr-coord",
    fullName: "Nguyễn Hồng Hạnh",
    email: "hanh.nguyen@liveagency.vn",
    phone: "0912345678",
    password: "123456",
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    role: "COORDINATOR",
    department: "Phòng Booking & Điều Phối Host",
    status: "ACTIVE",
    createdAt: "2026-02-15",
    permissions: {
      manageTalents: true,
      manageCampaigns: true,
      manageSchedule: true,
      viewReports: true,
      manageSettings: false,
      manageUsers: false,
      contactTalent: true,
    },
  },
  {
    id: "usr-acct",
    fullName: "Trần Đức Anh",
    email: "anh.tran@liveagency.vn",
    phone: "0909888777",
    password: "123456",
    avatarUrl: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    role: "ACCOUNTANT",
    department: "Phòng Kế Toán & Doanh Số",
    status: "ACTIVE",
    createdAt: "2026-03-01",
    permissions: {
      manageTalents: true,
      manageCampaigns: false,
      manageSchedule: false,
      viewReports: true,
      manageSettings: false,
      manageUsers: false,
      contactTalent: false,
    },
  },
  {
    id: "usr-staff",
    fullName: "Vũ Hoàng Yến",
    email: "yen.vu@liveagency.vn",
    phone: "0933111222",
    password: "123456",
    avatarUrl: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80",
    role: "STAFF",
    department: "Vận Hành Studio & Ca Live",
    status: "ACTIVE",
    createdAt: "2026-04-10",
    permissions: {
      manageTalents: false,
      manageCampaigns: false,
      manageSchedule: true,
      viewReports: false,
      manageSettings: false,
      manageUsers: false,
      contactTalent: false,
    },
  },
];

export const MOCK_CONVERSATIONS: ChatConversation[] = [
  {
    id: "conv-1",
    name: "Kênh Điều Phối Booking",
    isChannel: true,
    roleOrCategory: "4 Thành viên nhóm",
    unreadCount: 2,
    lastMessage: "Đã duyệt kịch bản ca live 9.9 cho Trang Hí",
    lastTimestamp: "10:45",
    memberIds: ["usr-admin", "usr-coord", "usr-acct", "usr-staff"],
    pinnedMessage: "Mục tiêu GMV ca live Mega Sale 9.9 Aura Glow là 800 triệu. Mã voucher áp dụng: MEGA99DEAL",
  },
  {
    id: "conv-2",
    name: "Kênh Vận Hành Studio Q7",
    isChannel: true,
    roleOrCategory: "3 Thành viên nhóm",
    unreadCount: 0,
    lastMessage: "Studio 1 đã setup xong góc máy quay Serum",
    lastTimestamp: "09:30",
    memberIds: ["usr-admin", "usr-coord", "usr-staff"],
    pinnedMessage: "Lịch kiểm tra ánh sáng và mic tại Studio 1 trước 30 phút mỗi ca trực.",
  },
  {
    id: "conv-3",
    name: "Trang Hí Live (Nguyễn Thu Trang)",
    isChannel: false,
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    roleOrCategory: "HOST Livestream",
    isOnline: true,
    lastMessage: "Em đã nhận sản phẩm mẫu Serum Skin Glow rồi ạ",
    lastTimestamp: "10:40",
    memberIds: ["usr-admin", "tal-001"],
  },
  {
    id: "conv-4",
    name: "Nguyễn Hồng Hạnh",
    isChannel: false,
    avatarUrl: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    roleOrCategory: "Coordinator",
    isOnline: true,
    lastMessage: "Hôm nay có 2 ca live mới của Brand HomeTech",
    lastTimestamp: "08:15",
    memberIds: ["usr-admin", "usr-coord"],
  },
  {
    id: "conv-5",
    name: "Nam TechReview (Lê Hoàng Nam)",
    isChannel: false,
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    roleOrCategory: "KOC Tech",
    isOnline: false,
    lastMessage: "Dạ ok anh, 14h chiều em qua Studio test nồi chiên",
    lastTimestamp: "Hôm qua",
    memberIds: ["usr-admin", "tal-002"],
  },
];

export const MOCK_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  "conv-1": [
    {
      id: "msg-1",
      conversationId: "conv-1",
      senderId: "usr-coord",
      senderName: "Nguyễn Hồng Hạnh",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderRole: "COORDINATOR",
      content: "Mọi người chú ý ca live 9.9 đợt này của Aura Glow nhé, mục tiêu GMV là 800 triệu.",
      timestamp: "10:15",
    },
    {
      id: "msg-2",
      conversationId: "conv-1",
      senderId: "usr-admin",
      senderName: "Phạm Quốc Hùng",
      senderAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      senderRole: "ADMIN",
      content: "Nhớ nhắc Host đẩy mạnh deal Serum Skin Glow Mua 1 Tặng 1 trong 45 phút đầu.",
      timestamp: "10:30",
      isMe: true,
    },
    {
      id: "msg-3",
      conversationId: "conv-1",
      senderId: "usr-coord",
      senderName: "Nguyễn Hồng Hạnh",
      senderAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
      senderRole: "COORDINATOR",
      content: "Đã duyệt kịch bản ca live 9.9 cho Trang Hí. Kèm thêm mã voucher giảm 30% MEGA99DEAL.",
      timestamp: "10:45",
      attachedSkuName: "Serum Phục Hồi Dưỡng Sáng Skin Glow 30ml (AG-SERUM-30)",
    },
  ],
  "conv-3": [
    {
      id: "msg-301",
      conversationId: "conv-3",
      senderId: "tal-001",
      senderName: "Trang Hí Live",
      senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      senderRole: "HOST",
      content: "Anh ơi, sản phẩm mẫu Serum Skin Glow bên Brand giao sang chưa ạ?",
      timestamp: "10:20",
    },
    {
      id: "msg-302",
      conversationId: "conv-3",
      senderId: "usr-admin",
      senderName: "Phạm Quốc Hùng",
      senderAvatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&auto=format&fit=crop&q=80",
      senderRole: "ADMIN",
      content: "Bên GHN báo đơn vđ GHN-89201948 đang phát rồi em nhé.",
      timestamp: "10:25",
      isMe: true,
    },
    {
      id: "msg-303",
      conversationId: "conv-3",
      senderId: "tal-001",
      senderName: "Trang Hí Live",
      senderAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
      senderRole: "HOST",
      content: "Em đã nhận sản phẩm mẫu Serum Skin Glow rồi ạ. Ca sáng mai 9h em sẵn sàng live!",
      timestamp: "10:40",
    },
  ],
};

export const MOCK_TALENTS: Talent[] = [
  {
    id: "tal-001",
    fullName: "Nguyễn Thu Trang",
    stageName: "Trang Hí Live",
    talentType: "HOST",
    phone: "0987654321",
    email: "trang.nguyen@liveagency.vn",
    zalo: "0987654321",
    address: "Studio 1, Quận 7, TP. Hồ Chí Minh",
    avatarUrl: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    categories: ["Thời trang", "Mỹ phẩm", "Mẹ & Bé"],
    tags: ["Chốt đơn nhanh", "Năng lượng cao", "Cực duyên"],
    channels: [
      { platform: "TIKTOK_LIVE", handle: "@tranghilive", followers: 450000, avgViews: 12000 },
      { platform: "SHOPEE_LIVE", handle: "tranghi_official", followers: 180000, avgViews: 8000 }
    ],
    internalRating: 4.9,
    avgGmvPerHour: 45000000,
    avgViewsPerVideo: 25000,
    fixedRatePerShift: 2500000,
    videoRate: 5000000,
    affiliateCommission: 8.0,
    exclusivityBrands: ["Brand CosmeA"],
    taxCode: "0319998881",
    bankName: "MB Bank",
    accountNumber: "999988886666",
    status: "AVAILABLE",
    mediaList: [
      {
        id: "med-101",
        type: "IMAGE_GMV",
        title: "Báo cáo GMV Bùng Nổ Ca Live Mega Sale 8.8 (TikTok Live)",
        url: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?w=800&auto=format&fit=crop&q=80",
        gmvAmount: 68500000,
        sessionDate: "2026-08-01",
        platform: "TIKTOK_LIVE",
      },
      {
        id: "med-102",
        type: "IMAGE_GMV",
        title: "Ảnh Đối Soát Doanh Số Shopee Live Khung Giờ Vàng 8.8",
        url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
        gmvAmount: 45000000,
        sessionDate: "2026-08-08",
        platform: "SHOPEE_LIVE",
      },
      {
        id: "med-103",
        type: "VIDEO_LIVE",
        title: "Video Clip Cut: Kỹ Năng Chốt Deal Mua 1 Tặng 1 Serum Skin Glow",
        url: "https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.mp4",
        thumbnailUrl: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=800&auto=format&fit=crop&q=80",
        sessionDate: "2026-08-01",
        platform: "TIKTOK_LIVE",
      },
      {
        id: "med-104",
        type: "VIDEO_LIVE",
        title: "Video Cut Highlight: Ca Live Mẫu Mỹ Phẩm Aura Glow (Chốt 1.200 đơn)",
        url: "https://vjs.zencdn.net/v/oceans.mp4",
        thumbnailUrl: "https://images.unsplash.com/photo-1522337360788-8b13dee7a37e?w=800&auto=format&fit=crop&q=80",
        sessionDate: "2026-08-08",
        platform: "SHOPEE_LIVE",
      },
    ],
  },
  {
    id: "tal-002",
    fullName: "Lê Hoàng Nam",
    stageName: "Nam TechReview",
    talentType: "KOC",
    phone: "0912345678",
    email: "nam.tech@kocvn.com",
    zalo: "0912345678",
    address: "Quận Cầu Giấy, Hà Nội",
    avatarUrl: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80",
    categories: ["Công nghệ", "Gia dụng", "Đồ chơi số"],
    tags: ["Review chi tiết", "Khách quan", "Quay phim đẹp"],
    channels: [
      { platform: "TIKTOK_LIVE", handle: "@namtechreview", followers: 820000, avgViews: 65000 },
      { platform: "SHOPEE_LIVE", handle: "NamTechOfficial", followers: 310000, avgViews: 45000 }
    ],
    internalRating: 4.8,
    avgGmvPerHour: 28000000,
    avgViewsPerVideo: 150000,
    fixedRatePerShift: 3500000,
    videoRate: 8000000,
    affiliateCommission: 12.0,
    exclusivityBrands: ["Hãng PhoneX"],
    taxCode: "0319998882",
    bankName: "Techcombank",
    accountNumber: "190333221144",
    status: "AVAILABLE",
    mediaList: [
      {
        id: "med-201",
        type: "IMAGE_GMV",
        title: "Báo cáo Doanh số Nồi Chiên Không Dầu HomeTech 5.5L",
        url: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=800&auto=format&fit=crop&q=80",
        gmvAmount: 52000000,
        sessionDate: "2026-07-20",
        platform: "SHOPEE_LIVE",
      },
      {
        id: "med-202",
        type: "VIDEO_LIVE",
        title: "Video Live Chiên Gà Trực Tiếp Trong Nồi Chiên 5.5L (Viral 65K Views)",
        url: "https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4",
        thumbnailUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=800&auto=format&fit=crop&q=80",
        sessionDate: "2026-07-20",
        platform: "TIKTOK_LIVE",
      },
    ],
  },
  {
    id: "tal-003",
    fullName: "Phạm Minh Anh",
    stageName: "Minh Anh Beauty",
    talentType: "KOL",
    phone: "0933445566",
    email: "booking@minhanh.vn",
    zalo: "0933445566",
    address: "Quận 1, TP. Hồ Chí Minh",
    avatarUrl: "https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80",
    categories: ["Mỹ phẩm", "Thời trang", "Skincare"],
    tags: ["Sang chảnh", "KOL A-List", "Viral"],
    channels: [
      { platform: "TIKTOK_LIVE", handle: "@minhanh.beauty", followers: 1200000, avgViews: 95000 }
    ],
    internalRating: 5.0,
    avgGmvPerHour: 85000000,
    avgViewsPerVideo: 300000,
    fixedRatePerShift: 12000000,
    videoRate: 20000000,
    affiliateCommission: 15.0,
    exclusivityBrands: [],
    taxCode: "0319998883",
    bankName: "Vietcombank",
    accountNumber: "0071001122334",
    status: "BUSY",
    mediaList: [
      {
        id: "med-301",
        type: "IMAGE_GMV",
        title: "Báo cáo GMV Ca Kỷ Lục 2 Giờ Livestream Skincare (120 triệu đ)",
        url: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=800&auto=format&fit=crop&q=80",
        gmvAmount: 120000000,
        sessionDate: "2026-06-15",
        platform: "TIKTOK_LIVE",
      },
    ],
  },
  {
    id: "tal-004",
    fullName: "Vũ Bảo Ngọc",
    stageName: "Bảo Ngọc Lifestyle",
    talentType: "HYBRID",
    phone: "0944556677",
    email: "ngoc.vu@agency.vn",
    zalo: "0944556677",
    address: "Studio 2, Quận 7, TP. Hồ Chí Minh",
    avatarUrl: "https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=150&auto=format&fit=crop&q=80",
    categories: ["Thời trang", "FMCG", "Gia dụng"],
    tags: ["Livestream 6 tiếng", "Nhiệt tình", "Kỹ năng chốt"],
    channels: [
      { platform: "TIKTOK_LIVE", handle: "@baongoc_live", followers: 600000, avgViews: 22000 },
      { platform: "SHOPEE_LIVE", handle: "baongoc_shop", followers: 400000, avgViews: 18000 }
    ],
    internalRating: 4.7,
    avgGmvPerHour: 55000000,
    avgViewsPerVideo: 45000,
    fixedRatePerShift: 4000000,
    videoRate: 7000000,
    affiliateCommission: 10.0,
    exclusivityBrands: ["Brand HomeCare"],
    taxCode: "0319998884",
    bankName: "VPBank",
    accountNumber: "888899990000",
    status: "AVAILABLE",
    mediaList: [
      {
        id: "med-401",
        type: "IMAGE_GMV",
        title: "Ảnh GMV Ca Live marathon 6 Tiếng Chốt 78 Triệu đ",
        url: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&auto=format&fit=crop&q=80",
        gmvAmount: 78000000,
        sessionDate: "2026-07-01",
        platform: "TIKTOK_LIVE",
      },
    ],
  }
];

export const MOCK_BRANDS: Brand[] = [
  {
    id: "brand-001",
    brandName: "Aura Glow Cosmetics",
    companyName: "Công Ty TNHH Mỹ Phẩm Aura Glow Việt Nam",
    taxCode: "0316789012",
    industry: "Mỹ phẩm & Skincare",
    contactPerson: "Chị Thảo (Brand Manager)",
    contactPhone: "0909123456",
    contactEmail: "thao.nguyen@auraglow.vn",
    contractStatus: "ACTIVE",
    skusCount: 4
  },
  {
    id: "brand-002",
    brandName: "HomeTech Vietnam",
    companyName: "Công Ty Cổ Phần Thiết Bị Gia Dụng HomeTech",
    taxCode: "0109876543",
    industry: "Gia dụng thông minh",
    contactPerson: "Anh Đức (Marketing Director)",
    contactPhone: "0988776655",
    contactEmail: "duc.vuhometech@gmail.com",
    contractStatus: "ACTIVE",
    skusCount: 3
  }
];

export const MOCK_SKUS: BrandSku[] = [
  {
    id: "sku-001",
    brandId: "brand-001",
    brandName: "Aura Glow Cosmetics",
    skuCode: "AG-SERUM-30",
    productName: "Serum Phục Hồi Dưỡng Sáng Skin Glow 30ml",
    category: "Mỹ phẩm",
    originalPrice: 450000,
    livePromoPrice: 299000,
    commissionRate: 18.0,
    keyUsp: "Cấp ẩm tức thì 72h, Niacinamide 10% dưỡng sáng",
    sampleStock: 15,
    imageUrl: "https://images.unsplash.com/photo-1620916566398-39f1143ab7be?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "sku-002",
    brandId: "brand-001",
    brandName: "Aura Glow Cosmetics",
    skuCode: "AG-SUN-50",
    productName: "Kem Chống Nắng Phổ Rộng SPF50+ PA++++ 50g",
    category: "Mỹ phẩm",
    originalPrice: 380000,
    livePromoPrice: 249000,
    commissionRate: 15.0,
    keyUsp: "Kiềm dầu 8 tiếng, Không rát da, Kháng nước",
    sampleStock: 22,
    imageUrl: "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=150&auto=format&fit=crop&q=80"
  },
  {
    id: "sku-003",
    brandId: "brand-002",
    brandName: "HomeTech Vietnam",
    skuCode: "HT-AIRFRY-5L",
    productName: "Nồi Chiên Không Dầu Thông Minh HomeTech 5.5L",
    category: "Gia dụng",
    originalPrice: 2200000,
    livePromoPrice: 1390000,
    commissionRate: 10.0,
    keyUsp: "Công nghệ chiên Rapid Air 360, Mặt kính quan sát",
    sampleStock: 8,
    imageUrl: "https://images.unsplash.com/photo-1585515320310-259814833e62?w=150&auto=format&fit=crop&q=80"
  }
];

export const MOCK_CAMPAIGNS: BookingCampaign[] = [
  {
    id: "cam-001",
    brandId: "brand-001",
    brandName: "Aura Glow Cosmetics",
    campaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    budget: 150000000,
    targetGmv: 800000000,
    startDate: "2026-08-01",
    endDate: "2026-08-10",
    shiftsCount: 4,
    description: "Chiến dịch livestream bùng nổ doanh số đẩy mạnh các SKU chủ lực của thương hiệu Aura Glow với deal ưu đãi mua 1 tặng 1 trong khung giờ vàng.",
    scriptUrl: "https://docs.google.com/document/d/1aura-glow-mega-sale-script/edit"
  },
  {
    id: "cam-002",
    brandId: "brand-002",
    brandName: "HomeTech Vietnam",
    campaignName: "Chiến Dịch Đổi Mới Bếp Hè 2026",
    budget: 90000000,
    targetGmv: 450000000,
    startDate: "2026-08-15",
    endDate: "2026-08-25",
    shiftsCount: 2,
    description: "Chiến dịch livestream gia dụng thông minh cho HomeTech Vietnam.",
    scriptUrl: "https://docs.google.com/document/d/1hometech-live-script/edit"
  }
];

export const MOCK_SHIFTS: BookingShift[] = [
  {
    id: "shift-001",
    campaignId: "cam-001",
    campaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    brandName: "Aura Glow Cosmetics",
    talentId: "tal-001",
    talentName: "Trang Hí Live",
    talentType: "HOST",
    platform: "TIKTOK_LIVE",
    location: "Studio 1 - Q7",
    date: "2026-08-01",
    startTime: "09:00",
    endTime: "12:00",
    shiftStatus: "COMPLETED",
    assignedSkus: [MOCK_SKUS[0], MOCK_SKUS[1]],
    actualGmv: 68500000,
    actualViews: 14500,
    peakConcurrent: 890,
    scriptUrl: "https://docs.google.com/document/d/1aura-glow-mega-sale-script/edit"
  },
  {
    id: "shift-002",
    campaignId: "cam-001",
    campaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    brandName: "Aura Glow Cosmetics",
    talentId: "tal-001",
    talentName: "Trang Hí Live",
    talentType: "HOST",
    platform: "SHOPEE_LIVE",
    location: "Studio 1 - Q7",
    date: "2026-08-08",
    startTime: "09:00",
    endTime: "12:00",
    shiftStatus: "COMPLETED",
    assignedSkus: [MOCK_SKUS[0], MOCK_SKUS[1]],
    actualGmv: 45000000,
    actualViews: 18500,
    peakConcurrent: 1200,
    scriptUrl: "https://docs.google.com/document/d/1aura-glow-mega-sale-script/edit"
  },
  {
    id: "shift-003",
    campaignId: "cam-001",
    campaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    brandName: "Aura Glow Cosmetics",
    talentId: "tal-001",
    talentName: "Trang Hí Live",
    talentType: "HOST",
    platform: "SHOPEE_LIVE",
    location: "Studio 1 - Q7",
    date: "2026-08-28",
    startTime: "09:00",
    endTime: "12:00",
    shiftStatus: "COMPLETED",
    assignedSkus: [MOCK_SKUS[0], MOCK_SKUS[1]],
    actualGmv: 45000000,
    actualViews: 18500,
    peakConcurrent: 1200,
    scriptUrl: "https://docs.google.com/document/d/1aura-glow-mega-sale-script/edit"
  },
  {
    id: "shift-004",
    campaignId: "cam-001",
    campaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    brandName: "Aura Glow Cosmetics",
    talentId: "tal-001",
    talentName: "Trang Hí Live",
    talentType: "HOST",
    platform: "TIKTOK_LIVE",
    location: "Studio 1 - Q7",
    date: "2026-09-08",
    startTime: "09:00",
    endTime: "12:00",
    shiftStatus: "COMPLETED",
    assignedSkus: [MOCK_SKUS[0], MOCK_SKUS[1]],
    actualGmv: 45000000,
    actualViews: 18500,
    peakConcurrent: 1200,
    scriptUrl: "https://docs.google.com/document/d/1aura-glow-mega-sale-script/edit"
  }
];

export const MOCK_TASKS: TaskItem[] = [
  {
    id: "task-001",
    title: "Chốt danh sách Host & KOC cho chiến dịch Mega Sale Aura Glow 8.8",
    description: "Liên hệ làm việc với 3 Host và 2 KOC để xếp lịch livestream cho đợt flash sale ngày 8/8.",
    assigneeId: "usr-002",
    assigneeName: "Trần Minh Đức",
    assigneeAvatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80",
    assigneeRole: "COORDINATOR",
    priority: "HIGH",
    status: "IN_PROGRESS",
    dueDate: "2026-08-05",
    createdAt: "2026-08-01",
    relatedCampaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
    relatedTalentName: "Trang Hí Live",
  },
  {
    id: "task-002",
    title: "Gửi mẫu sản phẩm Nồi chiên không dầu cho Nam TechReview",
    description: "Đóng gói 2 sản phẩm mẫu SKU-HT-AIR-01 và gửi dịch vụ hỏa tốc ra Hà Nội cho KOC.",
    assigneeId: "usr-004",
    assigneeName: "Nguyễn Văn Hùng",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    assigneeRole: "STAFF",
    priority: "MEDIUM",
    status: "TODO",
    dueDate: "2026-08-04",
    createdAt: "2026-08-01",
    relatedCampaignName: "Trải Nghiệm Gia Dụng Thông Minh HomeTech",
    relatedTalentName: "Nam TechReview",
  },
  {
    id: "task-003",
    title: "Kiểm tra đối soát doanh số ca live Shopee 8.8 với Kế toán Brand",
    description: "Xuất dữ liệu GMV thực tế 45.000.000đ ca live 8.8 và gửi hóa đơn cho phía Aura Glow.",
    assigneeId: "usr-003",
    assigneeName: "Lê Thị Mai",
    assigneeAvatar: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150&auto=format&fit=crop&q=80",
    assigneeRole: "ACCOUNTANT",
    priority: "HIGH",
    status: "REVIEW",
    dueDate: "2026-08-10",
    createdAt: "2026-08-08",
    relatedCampaignName: "Mega Sale 8.8 - Bùng Nổ Dưỡng Sáng",
  },
  {
    id: "task-004",
    title: "Setup thiết bị ánh sáng & mic cài áo cho Studio 1",
    description: "Kiểm tra hệ thống đèn livestream Godox và mic không dây Saramonic trước ca 9h sáng.",
    assigneeId: "usr-004",
    assigneeName: "Nguyễn Văn Hùng",
    assigneeAvatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80",
    assigneeRole: "STAFF",
    priority: "LOW",
    status: "DONE",
    dueDate: "2026-08-01",
    createdAt: "2026-07-31",
  },
];
