"use client";

import React from "react";
import Link from "next/link";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { TalentBadge } from "@/components/talents/talent-badge";
import { useCrmStore } from "@/lib/store";
import { formatVND } from "@/lib/utils";
import {
  TrendingUp,
  Users,
  CalendarCheck,
  Building2,
  Tv,
  ArrowUpRight,
  Sparkles,
} from "lucide-react";
import {
  ResponsiveContainer,
  BarChart,
  Bar,
  XAxis,
  YAxis,
  Tooltip,
  CartesianGrid,
} from "recharts";

export default function DashboardOverview() {
  const { talents, brands, shifts, campaigns } = useCrmStore();

  // Strict Real Data Calculation (Default 0 if empty)
  const totalGmvReal = shifts.reduce((sum, s) => sum + (s.actualGmv || 0), 0);
  const completedShifts = shifts.filter((s) => s.shiftStatus === "COMPLETED" || s.actualGmv > 0).length;

  const tiktokGmv = shifts
    .filter((s) => s.platform === "TIKTOK_LIVE")
    .reduce((sum, s) => sum + (s.actualGmv || 0), 0);

  const shopeeGmv = shifts
    .filter((s) => s.platform === "SHOPEE_LIVE")
    .reduce((sum, s) => sum + (s.actualGmv || 0), 0);

  const fbGmv = shifts
    .filter((s) => s.platform === "FACEBOOK_LIVE")
    .reduce((sum, s) => sum + (s.actualGmv || 0), 0);

  const chartData = [
    { platform: "TikTok Live", gmv: tiktokGmv },
    { platform: "Shopee Live", gmv: shopeeGmv },
    { platform: "FB Live", gmv: fbGmv },
  ];

  // Calculate real GMV generated by each Talent for ranking
  const talentsWithRealPerformance = talents.map((t) => {
    const talentShifts = shifts.filter((s) => s.talentId === t.id);
    const realGmv = talentShifts.reduce((sum, s) => sum + (s.actualGmv || 0), 0);
    return {
      ...t,
      realGmv,
    };
  }).sort((a, b) => b.realGmv - a.realGmv);

  return (
    <div className="space-y-6">
      {/* KPI Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card className="border-slate-200 dark:border-slate-800">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-slate-500 tracking-wider">
              Tổng GMV Thực Tế
            </CardTitle>
            <div className="w-8 h-8 rounded-lg bg-indigo-50 dark:bg-indigo-950 flex items-center justify-center text-indigo-600">
              <TrendingUp className="w-4 h-4" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900 dark:text-white">
              {formatVND(totalGmvReal)}
            </div>
            <div className="flex items-center text-xs text-emerald-600 font-medium mt-1">
              <ArrowUpRight className="w-3.5 h-3.5 mr-0.5" />
              {completedShifts > 0 ? `Tổng từ ${completedShifts} ca live hoàn thành` : "Chưa có dữ liệu ca live hoàn thành"}
            </div>
          </CardContent>
        </Card>

        <Card className="border-slate-200 dark:border-slate-800">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-slate-500 tracking-wider">
              Tổng Talent Quản Lý
            </CardTitle>
            <div className="w-8 h-8 rounded-lg bg-violet-50 dark:bg-violet-950 flex items-center justify-center text-violet-600">
              <Users className="w-4 h-4" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900 dark:text-white">
              {talents.length} Talent
            </div>
            <p className="text-xs text-slate-500 mt-1">
              {talents.filter((t) => t.talentType === "HOST").length} Host, {talents.filter((t) => t.talentType === "KOC").length} KOC, {talents.filter((t) => t.talentType === "KOL").length} KOL
            </p>
          </CardContent>
        </Card>

        <Card className="border-slate-200 dark:border-slate-800">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-slate-500 tracking-wider">
              Ca Booking Đã Lên Lịch
            </CardTitle>
            <div className="w-8 h-8 rounded-lg bg-amber-50 dark:bg-amber-950 flex items-center justify-center text-amber-600">
              <CalendarCheck className="w-4 h-4" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900 dark:text-white">
              {shifts.length} Ca Live
            </div>
            <p className="text-xs text-slate-500 mt-1">
              {completedShifts} đã hoàn thành, {Math.max(0, shifts.length - completedShifts)} sắp diễn ra
            </p>
          </CardContent>
        </Card>

        <Card className="border-slate-200 dark:border-slate-800">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-xs font-semibold uppercase text-slate-500 tracking-wider">
              Brand Đang Hợp Tác
            </CardTitle>
            <div className="w-8 h-8 rounded-lg bg-emerald-50 dark:bg-emerald-950 flex items-center justify-center text-emerald-600">
              <Building2 className="w-4 h-4" />
            </div>
          </CardHeader>
          <CardContent>
            <div className="text-2xl font-bold text-slate-900 dark:text-white">
              {brands.length} Thương Hiệu
            </div>
            <p className="text-xs text-slate-500 mt-1">
              {campaigns.length} Chiến dịch đang hoạt động
            </p>
          </CardContent>
        </Card>
      </div>

      {/* Main Charts & Widgets Grid */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Revenue Chart */}
        <Card className="lg:col-span-2 border-slate-200 dark:border-slate-800">
          <CardHeader>
            <CardTitle className="text-base font-bold">
              Phân Bổ GMV Theo Kênh Livestream
            </CardTitle>
            <CardDescription>
              Tỷ trọng doanh số đóng góp từ TikTok Live, Shopee Live & Facebook Live (Số liệu thực tế)
            </CardDescription>
          </CardHeader>
          <CardContent className="h-72">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData}>
                <CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e2e8f0" />
                <XAxis dataKey="platform" tick={{ fontSize: 12 }} />
                <YAxis tickFormatter={(val) => `${val / 1000000}M`} tick={{ fontSize: 11 }} />
                <Tooltip formatter={(value: number) => formatVND(value)} />
                <Bar dataKey="gmv" fill="#4f46e5" radius={[6, 6, 0, 0]} />
              </BarChart>
            </ResponsiveContainer>
          </CardContent>
        </Card>

        {/* Top Active Talents Widget */}
        <Card className="border-slate-200 dark:border-slate-800">
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <CardTitle className="text-base font-bold flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-amber-500" />
                Top Host / KOC Nổi Bật
              </CardTitle>
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {talentsWithRealPerformance.slice(0, 3).map((talent) => (
              <Link
                key={talent.id}
                href={`/talents/${talent.id}`}
                className="flex items-center justify-between p-3 rounded-lg border border-slate-100 dark:border-slate-800 bg-slate-50/50 dark:bg-slate-900/50 hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors"
              >
                <div className="flex items-center gap-3">
                  <img
                    src={talent.avatarUrl}
                    alt={talent.stageName}
                    className="w-10 h-10 rounded-full object-cover border border-slate-200"
                  />
                  <div>
                    <p className="font-bold text-xs text-slate-900 dark:text-white">
                      {talent.stageName}
                    </p>
                    <p className="text-[11px] text-slate-500">
                      GMV Thực Tế: <b className="text-emerald-600">{formatVND(talent.realGmv)}</b>
                    </p>
                  </div>
                </div>
                <TalentBadge type={talent.talentType} />
              </Link>
            ))}
          </CardContent>
        </Card>
      </div>

      {/* Upcoming Shifts Table */}
      <Card className="border-slate-200 dark:border-slate-800">
        <CardHeader>
          <CardTitle className="text-base font-bold flex items-center justify-between">
            <span>Ca Booking Livestream Hệ Thống ({shifts.length})</span>
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0 overflow-x-auto">
          <table className="w-full text-left text-xs border-collapse">
            <thead>
              <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-slate-900/50 text-slate-500 font-semibold whitespace-nowrap">
                <th className="p-4 whitespace-nowrap">Talent</th>
                <th className="p-4 whitespace-nowrap">Brand Đối Tác</th>
                <th className="p-4 whitespace-nowrap">Nền Tảng</th>
                <th className="p-4 whitespace-nowrap">Thời Gian Live</th>
                <th className="p-4 whitespace-nowrap">Địa Điểm</th>
                <th className="p-4 text-right whitespace-nowrap">GMV Thực Tế</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
              {shifts.map((shift) => {
                const talent = talents.find((t) => t.id === shift.talentId);
                return (
                  <tr key={shift.id} className="hover:bg-slate-50 dark:hover:bg-slate-900/50 whitespace-nowrap">
                    <td className="p-4 font-bold text-indigo-600 whitespace-nowrap">
                      <Link href={`/talents/${shift.talentId}`} className="hover:underline">
                        {shift.talentName}
                      </Link>
                    </td>
                    <td className="p-4 font-medium text-slate-900 dark:text-white whitespace-nowrap">{shift.brandName}</td>
                    <td className="p-4 whitespace-nowrap">
                      <span className="px-2 py-0.5 rounded font-bold text-[10px] bg-slate-100 text-slate-700 border">
                        {shift.platform === "TIKTOK_LIVE" ? "TikTok Live" : "Shopee Live"}
                      </span>
                    </td>
                    <td className="p-4 font-medium text-slate-600 dark:text-slate-300 whitespace-nowrap">
                      {shift.date} ({shift.startTime} - {shift.endTime})
                    </td>
                    <td className="p-4 font-medium whitespace-nowrap">{shift.location}</td>
                    <td className="p-4 text-right font-bold text-emerald-600 whitespace-nowrap">
                      {formatVND(shift.actualGmv || 0)}
                    </td>
                  </tr>
                );
              })}
            </tbody>
          </table>
        </CardContent>
      </Card>
    </div>
  );
}
